from abc import ABC, abstractmethod
from typing import List, Optional
from nfc.domain.nfc import NFC

class NFCRepository(ABC):
    @abstractmethod
    def registrar(self, entidad: NFC) -> NFC: ...
    @abstractmethod
    def eliminar(self, id_nfc: str) -> bool: ...
    @abstractmethod
    def obtener_por_id(self, id_nfc: str) -> Optional[NFC]: ...
    @abstractmethod
    def obtener_todos(self) -> List[NFC]: ...
    @abstractmethod
    def actualizar_estado(self, id_nfc: int, estado: str) -> bool: ...
